version: 2
updates:
  - package-ecosystem: docker
    directory: /
    cooldown:
      default-days: 0
    schedule:
      interval: weekly
    groups:
      keycloak-base:
        patterns:
          - quay.io/keycloak/keycloak
